version: '3.7'
name: pocket-js-server
services: 
  pg: 
    image: bitnami/postgresql:latest
    ports: 
      - '5433:5432'
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inorbit